### ISSUE TITLE
failed: [k8s-master01] (item=registry.custom.local:12480/kubeadm-ha/pause:3.5) 

### ISSUE THREAD

**Issue by chen5041** [TimeBye/kubeadm-ha#115]
**缺陷描述**

清晰而简明的描述缺陷是什么。

**环境 (请填写以下信息):**
kubeadm-ha-1.22.10-amd64.tar

执行下面括号中的命令，提交返回结果

[root@k8s-master01 ansible-kubeadm]# docker exec -it kubeadm-ha  ansible-playbook -i my-cluster/hosts.s-master.hostname.ini   -e @my-cluster/variables.yaml 90-init-cluster.yml -vvv 

**如何复现**

复现的步骤：

1. 第一步：编写 inventory.ini 文件，内容如下
    ```ini
   [root@k8s-master01 ansible-kubeadm]# cat    my-cluster/hosts.s-master.hostname.ini 
    ; 将所有节点的信息在这里填写
    ;    第一个字段                  为 kubernetes 节点 nodeName，注意必须由小写字母、数字，“-”或“.”组成，并且必须以小写字母或数字开头和结尾
    ;    第二个字段 ansible_host     为节点内网IP
    ;    第三个字段 ansible_port     为节点 sshd 监听端口
    ;    第四个字段 ansible_user     为节点远程登录用户名
    ;    第五个字段 ansible_ssh_pass 为节点远程登录用户密码 
    [all]
    k8s-master01 ansible_host=192.168.92.10 ansible_port=22 ansible_user="root" ansible_ssh_pass="1"
    k8s-node01 ansible_host=192.168.92.11 ansible_port=22 ansible_user="root" ansible_ssh_pass="1"
    k8s-node02 ansible_host=192.168.92.12 ansible_port=22 ansible_user="root" ansible_ssh_pass="1"

    ; 单 master 节点不需要进行负载均衡，lb节点组留空。
    [lb]

    ; 注意etcd集群必须是1,3,5,7...奇数个节点
    [etcd]
    k8s-master01

    [kube-master]
    k8s-master01

    [kube-worker]
    k8s-node01
    k8s-node02

    ; 预留组，后续添加master节点使用
    [new-master]

    ; 预留组，后续添加worker节点使用
    [new-worker]

    ; 预留组，后续添加etcd节点使用
    [new-etcd]

    ; 预留组，后续删除worker角色使用
    [del-worker]

    ; 预留组，后续删除master角色使用
    [del-master]

    ; 预留组，后续删除etcd角色使用
    [del-etcd]

    ; 预留组，后续删除节点使用
    [del-node]

    ;-------------------------------------- 以下为基础信息配置 ------------------------------------;
    [all:vars]
    ; 是否跳过节点物理资源校验，Master节点要求2c2g以上，Worker节点要求2c4g以上
    skip_verify_node=false
    ; kubernetes版本
    kube_version="1.22.10"

    ; 容器运行时类型，可选项：containerd，docker；默认 containerd
    container_manager="docker"

    ; 负载均衡器
    ;   有 nginx、openresty、haproxy、envoy  和 slb 可选，默认使用 nginx
    ;   为什么单 master 集群 apiserver 也使用了负载均衡请参与此讨论： https://github.com/TimeBye/kubeadm-ha/issues/8
    lb_mode="nginx"
    ; 使用负载均衡后集群 apiserver ip，设置 lb_kube_apiserver_ip 变量，则启用负载均衡器 + keepalived
    ; lb_kube_apiserver_ip="192.168.56.15"
    ; 使用负载均衡后集群 apiserver port
    lb_kube_apiserver_port="8443"

    ; 网段选择：pod 和 service 的网段不能与服务器网段重叠，
    ; 若有重叠请配置 `kube_pod_subnet` 和 `kube_service_subnet` 变量设置 pod 和 service 的网段，示例参考：
    ;    如果服务器网段为：10.0.0.1/8
    ;       pod 网段可设置为：192.168.0.0/18
    ;       service 网段可设置为 192.168.64.0/18
    ;    如果服务器网段为：172.16.0.1/12
    ;       pod 网段可设置为：10.244.0.0/18
    ;       service 网段可设置为 10.244.64.0/18
    ;    如果服务器网段为：192.168.0.1/16
    ;       pod 网段可设置为：10.244.0.0/18
    ;       service 网段可设置为 10.244.64.0/18
    ; 集群pod ip段，默认掩码位 18 即 16384 个ip
    kube_pod_subnet="10.244.0.0/18"
    ; 集群service ip段
    kube_service_subnet="10.244.64.0/18"
    ; 分配给节点的 pod 子网掩码位，默认为 24 即 256 个ip，故使用这些默认值可以纳管 16384/256=64 个节点。
    kube_network_node_prefix="24"

    ; node节点最大 pod 数。数量与分配给节点的 pod 子网有关，ip 数应大于 pod 数。
    ; https://cloud.google.com/kubernetes-engine/docs/how-to/flexible-pod-cidr
    kube_max_pods="110"

    ; 集群网络插件，目前支持flannel,calico
    network_plugin="calico"

    ; 若服务器磁盘分为系统盘与数据盘，请修改以下路径至数据盘自定义的目录。
    ; Kubelet 根目录
    kubelet_root_dir="/var/lib/kubelet"
    ; docker容器存储目录
    docker_storage_dir="/var/lib/docker"
    ; containerd容器存储目录
    containerd_storage_dir="/var/lib/containerd"
    ; Etcd 数据根目录
    etcd_data_dir="/var/lib/etcd"

    ......
    ```

2. 第二步：编写 variables.yaml 文件，内容如下
    ```yaml
    custom_hosts:
        "192.168.92.10": 
        - "registry.custom.local"
        - "yum.custom.local"
    base_yum_repo: http://yum.custom.local:12480/yum/
    epel_yum_repo: http://yum.custom.local:12480/yum/
    docker_yum_repo: http://yum.custom.local:12480/yum/
    kubernetes_yum_repo: http://yum.custom.local:12480/yum/
    docker_insecure_registries:
        - "registry.custom.local:12480"
    containerd_registries:
        "registry.custom.local:12480": "http://registry.custom.local:12480"
    kube_image_repository: registry.custom.local:12480/kubeadm-ha
    container_manager: docker
    kube_certs_expired: 3650
    kube_ca_certs_expired: 36500
    pod_infra_container_image: "{{ kube_image_repository }}/pause:3.7"
    kube_version: 1.22.10
    kube_service_node_port_range: 30000-32767
    kube_cpu_reserved: 100m
    kube_memory_reserved: 256M
    kube_ephemeral_storage_reserved: 1G
    system_reserved_enabled: true
    system_cpu_reserved: 500m
    system_memory_reserved: 512M
    system_ephemeral_storage_reserved: 10G
    kube_proxy_mode: ipvs
    ......
    ```

3. 第三步：执行部署命令，命令如下
    ```yaml
    ansible-playbook -i inventory.ini -e @variables.yaml 90-init-cluster.yml
    ```

4. 出现错误
    ```
    failed: [k8s-master01] (item=registry.custom.local:12480/kubeadm-ha/pause:3.5) => {
    "ansible_loop_var": "item",
    "changed": true,
    "cmd": "docker pull registry.custom.local:12480/kubeadm-ha/pause:3.5",
    "delta": "0:00:00.043763",
    "end": "2022-09-15 14:46:22.344907",
    "invocation": {
        "module_args": {
            "_raw_params": "docker pull registry.custom.local:12480/kubeadm-ha/pause:3.5",
            "_uses_shell": true,
            "argv": null,
            "chdir": null,
            "creates": null,
            "executable": null,
            "removes": null,
            "stdin": null,
            "stdin_add_newline": true,
            "strip_empty_ends": true,
            "warn": true
        }
    },
    "item": "registry.custom.local:12480/kubeadm-ha/pause:3.5",
    "msg": "non-zero return code",
    "rc": 1,
    "start": "2022-09-15 14:46:22.301144",
    "stderr": "Error response from daemon: manifest for registry.custom.local:12480/kubeadm-ha/pause:3.5 not found: manifest unknown: manifest unknown",
    "stderr_lines": [
        "Error response from daemon: manifest for registry.custom.local:12480/kubeadm-ha/pause:3.5 not found: manifest unknown: manifest unknown"
    ],
    "stdout": "",
    "stdout_lines": []
    }

    NO MORE HOSTS LEFT ********************************************************************************************************************************************************

    PLAY RECAP ****************************************************************************************************************************************************************
    k8s-master01               : ok=184  changed=64   unreachable=0    failed=1    skipped=59   rescued=0    ignored=0   
    k8s-node01                 : ok=79   changed=26   unreachable=0    failed=0    skipped=28   rescued=0    ignored=0   
    k8s-node02                 : ok=79   changed=26   unreachable=0    failed=0    skipped=28   rescued=0    ignored=0   

    ```

**预期结果**

这里为什么会去拉取pause:3.5镜像呢? 已经定义了pause:3.7不生效，还是会拉取pause:3.5

**屏幕截图**

如果可以的话，添加屏幕截图来帮助解释你的问题。

**其他事项**

在此处添加有关该问题的任何其他事项。
