### ISSUE TITLE
controller-manager、scheduler、 启动参数为--port=0    ，监控无法搜集metrics

### ISSUE THREAD

**Issue by li-sen** [TimeBye/kubeadm-ha#84]
**缺陷描述**
这样设置基于什么考虑？安全？

**Comment by TimeBye** [comment]
是的，

**Comment by li-sen** [comment]
怎么在ansible脚本中覆盖去掉？

**Comment by TimeBye** [comment]
### 情况一：集群已部署完成

修改各master节点以下配置文件
- /etc/kubernetes/manifests/kube-controller-manager.yaml
    ```diff
    -     - --bind-address=127.0.0.1
    +     - --bind-address=0.0.0.0
    ```

- /etc/kubernetes/manifests/kube-scheduler.yaml
    ```diff
    -     - --bind-address=127.0.0.1
    +     - --bind-address=0.0.0.0
    ```

### 情况二：集群未部署或版本升级时
- 修改安装配置文件 variables.yaml

    ```yaml
    kube_kubeadm_controller_extra_args:
    bind-address: 0.0.0.0
    kube_kubeadm_scheduler_extra_args:
    bind-address: 0.0.0.0
    ```
