### ISSUE TITLE
添加一条Ingress 规则时，添加不了

### ISSUE THREAD

**Issue by wpjscc** [TimeBye/kubeadm-ha#94]
配置文件 nginx-ingress.yaml
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nginx-ingress
spec:
  rules:
    - host: k8s.domin.com
      http:
        paths:
          - backend:
              serviceName: nginx
              servicePort: 80
            path: /
```
当应用时报错
```
kubectl apply -f nginx-ingress.yaml
```
```
root@iZuf6dujyvsbfmnuhs23c8Z:~# cat nginx-ingress.yaml 
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nginx-ingress
spec:
  rules:
    - host: k8s.wpjs.cc
      http:
        paths:
          - backend:
              serviceName: nginx
              servicePort: 80
            path: /
root@iZuf6dujyvsbfmnuhs23c8Z:~# kubectl apply -f nginx-ingress.yaml 
error: unable to recognize "nginx-ingress.yaml": no matches for kind "Ingress" in version "extensions/v1beta1"
```
